### ISSUE TITLE
2 additional fields and 1 modified field

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#15]
We will have 2 additional fields and 1 modified field:
1. Age (in years):
2. Date of Birth (date):
3. Date of test (date):

The rule follows: if 1 is filled 2 and 3 are disabled. If 2 is filled 3 must also be filled and 1 will be computed automatically.

**Comment by anandgavai** [comment]
Added fields, validation is remaining.

**Comment by anandgavai** [comment]
Further clarification @Nanouk123. Within the user interface its fine. However I wonder when the clinician is uploading the file how the behaviour is expected ?

**Comment by Nanouk123** [comment]
If I understand you correctly you're asking what happens if someone uploads an excel file with data?
I think you should ask for 'age in years' in the uploaded file. So these are researchers and all will have the variable 'age' specified. MOST will have information on date of birth and test but not all. Age is more common for researchers to use. So for them I would simply ignore date of birth and date of test.

So they upload a template with information on 'age' .the template gets filled out on the portal and 'date of birth' and 'date of test' will be disabled (because 'age' is filled). 

Is that a good plan?

**Comment by anandgavai** [comment]
Alright, So during file upload "Age" is compulsory and "testdate" and "birthdate" can be ignored from validation isnt it

**Comment by Nanouk123** [comment]
Id say so yes.

**Comment by mkuzak** [comment]
It is now implemented.
