### ISSUE TITLE
Only data from first patient is read from .txt file with multiple patients

### ISSUE THREAD

**Issue by ridderl** [andi-nl/ANDI-frontend#187]

**Comment by jvdzwaan** [comment]
@ridderl Can you please provide the text file?

**Comment by ridderl** [comment]
[patientdata.txt](https://github.com/andi-nl/ANDI-frontend/files/629028/patientdata.txt)
It turns out it is not the first, but only the second patient that is being read ....

**Comment by ridderl** [comment]
Attached is a text file with 3 patients. Only the last two are read ....
[patientdata (2).txt](https://github.com/andi-nl/ANDI-frontend/files/629032/patientdata.2.txt)

**Comment by jvdzwaan** [comment]
This file does not contain the column with info about the ranges of acceptable values. The app assumes this column is in the file and that's why the first patient is ignored. 

I propose we solve this problem by putting a message on the site (or even in the csv template) that tells the user not to delete this column.

**Comment by jvdzwaan** [comment]
Ah, I now see where this data comes from; it is the file you get when you export the patient data. I'll add an additional column to that one.

**Comment by ridderl** [comment]
Yes, indeed it was an file exported after filling in data online.
Sorry, I didn't explain well and overlooked your earlier comment ...
