### ISSUE TITLE
Text field containing terms and conditions should be scrollable.

### ISSUE THREAD

**Issue by mkuzak** [andi-nl/ANDI-frontend#188]
Terms and conditions occupy a lot of space. It's better to put them in a text area of fixed height and vertical scrolling.

**Comment by jvdzwaan** [comment]
I have discussed this with @JAvRZ (well not the option of putting them in a box with scrolling), so I'd like to hear his opinion before changing them. Joost, what do you think?

**Comment by mkuzak** [comment]
This is what we decided in the meeting last Thursday. @JAvRZ please confirm.

**Comment by JAvRZ** [comment]
I think we all agree that we want people to read them, or that it is at least reasonable to think that people have read them. There was one option in the meeting that was offered to hide it under a link to a different page. Mateusz and I were concerned that this effectively means that users will never ever read the terms and conditions. So that's why Mateusz was coming up with compromises that make the text less huge, without compromising the expectancy that people have read them. If you think it is unworkable or undesirable, I think we are open to better solutions.
