### ISSUE TITLE
Remove normative data versions 2015 and 2014

### ISSUE THREAD

**Issue by jvdzwaan** [andi-nl/ANDI-frontend#191]
`Error: non-numeric argument to mathematical function In call: sign(ANDImetadata[["mybestpowertransform"]][ANDImetadata[["uniqueid"]] %in% mydata[["uniqueid"]]])`

**Comment by JAvRZ** [comment]
My proposed solution is scrapping the current 2015 and 2014 directories, besides implementing #167 . Because I currently have no idea what is in those directories (never did to be honest), and what csv it uses to plot what normative data, so I can very well imagine that a mismatch between files occurs.

I think they were put there to demonstrate that earlier/older normative datasets could be selected, retrospectively adding 2014 and 2015 as examples of older versions.

**Comment by jvdzwaan** [comment]
Okay, I can do that. This means that there is only one normative data version left (so nothing to choose).

**Comment by JAvRZ** [comment]
If you want to keep the option, duplicating 2016 and renaming it 2015 is an option, come to think about it.

**Comment by jvdzwaan** [comment]
That would be confusing, no? 

The option of adding more normative data versions is still there, only without 2015 and 2014 there is only one option to choose from (2016). I'll just leave it like this.

**Comment by JAvRZ** [comment]
Agreed. That makes #167 a little less urgent, but definitely nice to have when new versions are indeed added.

**Comment by jvdzwaan** [comment]
Yes, that was very easy to add, so it is already in there :) 
Just wait for the new version to be put online
