### ISSUE TITLE
Downloading, completing + uploading template didn't work

### ISSUE THREAD

**Issue by ridderl** [andi-nl/ANDI-frontend#66]
- Select AVLT + [Next] + Download template
- Result:

```
Demographics
id
age
sex
education
AVLT-total_1_to_5
AVLT-delayed_recall_1_to_5
AVLT-recognition_1_to_5
```
- Completed the template:

```
Demographics,Patient 1
id,2
age,45
sex,male
education,Verhage 2
AVLT-total_1_to_5,40
AVLT-delayed_recall_1_to_5,20
AVLT-recognition_1_to_5,10
```
- Uploaded it to the website
- Result:
  - Browse button for uploading is then missing
  - Empty table, with additional fields instead of filled cells:

```
Demographics
id
age
birthdate
testdate
sex
education
AVLT-total_1_to_5
AVLT-delayed_recall_1_to_5
AVLT-recognition_1_to_5
AVLT-total_1_to_5,40
AVLT-delayed_recall_1_to_5,20
AVLT-recognition_1_to_5,10
```

**Comment by anandgavai** [comment]
The uploading of data has been changed from "," separated values to Dutch standard ";" separated values.

**Comment by ridderl** [comment]
Ah, indeed with ; instead of , it works OK. But, I guess we want this to work with comma separated files as well?
Also, after the upload, the button for (another) upload is gone. Is that on purpose?

**Comment by ridderl** [comment]
Also, the sex and education cells were still not filled

**Comment by anandgavai** [comment]
Sex needs to be 0, 1 and education needs to be values between 1 till 7 . The upload button was gone on request as it was a two step procedure, but will make it more clear.

**Comment by ridderl** [comment]
- OK, that works. Bottom line is that this needs to be clear for the user. (Maybe some explanation in the excel file? Ask Nathalie?)
- Download after filling the table online does not include the filled in data ...

**Comment by anandgavai** [comment]
. @Nanouk123  is working on text for every tab and it will be made clear by me on the selection as well !
. Download after filling the table functionality never existed. It is only for creating the template to be filled in by the clinician

**Comment by mkuzak** [comment]
@ridderl this should work now (in running cloud instance) please confirm and close if you think it's resolved.

**Comment by ridderl** [comment]
No, it doesn't work properly yet:
- If you download the template twice, the second time it is different from the first time (doubling the rows).
- Do we still expect the template to include completed testscores? At this moment it doesn't (If you first go Next, fill in some values, then go Previous and then download the template), but I thought we wanted to have the possibility to download the table including the completed scores. Therefore I thought it would be most logical to have the upload button on the first "tab" and the download button on the second.

**Comment by mkuzak** [comment]
Agree, does not work yet. @Nanouk123 do we want to be able to download template with filled in values?

**Comment by anandgavai** [comment]
If we want to have downloaded values then may be we can put this in a new requirement list ? @ridderl @Nanouk123  please confirm

**Comment by Nanouk123** [comment]
@mkuzak at some point we do want to download the excel files with the values. Because then clinicians can store them with their results and reupload them later (that's why we have the 'upload template' in the first tab for these exact people). 

I think some of these points overlap my comments on https://github.com/andi-nl/andi/issues/18#issuecomment-224606948 ?

**Comment by mkuzak** [comment]
@Nanouk123 @anandgavai @ridderl It's clear that this is a requirement then.

**Comment by Nanouk123** [comment]
Yes, it already was in the beginning (idealy we wanted to export PDF with the results (plots) and automatically download the csv for the uploaded patient(s). This because we want clinicians to re-evaluate the patient data. But it was too much work and ethically difficult to instate a log in system in which clinicians could save the patient data they have filled out in earlier sessions. 

So to avoid all that (you need permission from patients to keep their data online, security issues and such) we agreed that in the export you'd always include the excel/csv with the filled out data. So that for a next session they can quickly upload the file.

Does that make sense?

**Comment by mkuzak** [comment]
It does.

**Comment by anandgavai** [comment]
@Nanouk123  @ridderl If we would like to download template filled with values this would mean a lot of restructuring of the code !!!

**Comment by Nanouk123** [comment]
This was already a requirement in the first version. We can discuss it later today if you wish.

**Comment by mkuzak** [comment]
This has been fixed or changed. Downloading data goes into the new tab. Template should always be empty.
