### ISSUE TITLE
Remove range suggestion from the template.

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#78]
There needs to be a new column in the template. This filed should give information about variable format. For example, date dd/mm/yyyy, age in years, education between 1-7, sex 0,1 (with explanation what is 0 and what is 1).

**Comment by mkuzak** [comment]
The column has been added. @Nanouk123 @JAvRZ can you download a template and see if you agree with the implementation. If all is as it should be please close an issue.

**Comment by Nanouk123** [comment]
I would give the 'info' in the info box, not the ranges. Ranges get checked ont he website anyway plus the ranges are not always correct for each test (because we lack the formal information).
So from the 'golden template' I'd give the description.
(which is more info about the variable than the range). @JAvRZ ?

**Comment by JAvRZ** [comment]
I think we should split the discussion into a demographics part and a test variable part. Because for the demographics part, the ranges are very handy (I am always unsure if Sex is coded as 1-2, 0-1 or -1 1, so having that there is great). For the test ranges, I find them handy, but I understand Nan's point that those ranges can be confusing when test ranges are not logical (if there are 75 questions, and you have to fill in a score between 0-75, no-one gets confused. But in other cases, a limit might be confusing (like time limits)). But by all means, keep the demographic ranges.

**Comment by Nanouk123** [comment]
Yes for the demographics you can keep ranges but we could also just add this info in the goldentemplate? As info.. so how to code men/women for example. This is just as useful info as knowing that the 'AVLT-total' is a total over 5 trials (for example).

The ranges are in more cases illogical than logical (unfortunately) so I wouldn't like to put them up for display.

**Comment by mkuzak** [comment]
@JAvRZ @Nanouk123 can you please check if this does now work as expected or not.

**Comment by Nanouk123** [comment]
Can you pls send me an email with the link or attachment of what you want me to check?

**Comment by Nanouk123** [comment]
Im not quite sure what to check. but:

I have dld the template: Shows ranges for the tests which should be removed (discussed this with Ben).
Ranges for demo variables can stay (see my comment on 4th of July)

**Comment by mkuzak** [comment]
@JAvRZ correct me if I'm wrong, but during our last meeting Ben decided to keep the ranges in the template.

**Comment by Nanouk123** [comment]
My convo dates from 27-7 my last working day. Ben and I worked on the template (we changed a lot of the borders in the process).  So I hope you can soon start work on the latest golden template (with all andi variables and not just the example ones as we have now). Because this file alao has changes in what the website should or shouldn't accept.

Anyway if after this moment you guys decided to include borders again it would've been nice to have been notified.  I stick to my point that the borders in most cases are trivially chosen and dont help users at all (im more afraid they will be confused by them) 

I think Joost is on holidays

**Comment by mkuzak** [comment]
Well I have no preference, borders or not. During last meeting we looked at the template and I mentioned the borders will go away (as we decided earlier) and Ben said they should stay.

**Comment by Nanouk123** [comment]
See Bens mail. No borders in template or on website.  Only when added value exceeds these values

**Comment by Nanouk123** [comment]
Ill paste it here so there'll be no confusion in the future:

Dear Nathalie,
You're right. It's better to show a pop-up message when someone fills in an impossible value. Showing in advance borders that perhaps are not the actual ones may cause confusion.
Ciao,
Ben

**Comment by mkuzak** [comment]
Ok, I'm renaming this issue based on the decisions made.

**Comment by JAvRZ** [comment]
I'm pretty sure that these range suggestions have been removed, or at least, I don't see them anymore. Thanks, closing.
